CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- Таблица справочника навыков
CREATE TABLE IF NOT EXISTS skills (
    id SERIAL PRIMARY KEY,
    name VARCHAR(200) NOT NULL UNIQUE, -- название навыка
    category VARCHAR(30) NOT NULL, -- категория навыков (technical/tool/soft/language)
    created_at DATETIME NOT NULL -- время занесения данных в справочник
);

--  Связующая таблица "вакансия - навык"
CREATE TABLE IF NOT EXISTS vacancy_skills (
    vacancy_id UUID NOT NULL,
    skill_id INTEGER NOT NULL,
    is_required BOOLEAN DEFAULT false,
    priority SMALLINT DEFAULT 1 CHECK (priority BETWEEN 1 AND 5),
    PRIMARY KEY (vacancy_id, skill_id),
    FOREIGN KEY (vacancy_id) REFERENCES vacancies(id) ON DELETE CASCADE,
    FOREIGN KEY (skill_id) REFERENCES skills(id) ON DELETE CASCADE
);

-- Вставка 200 технического навыков --
INSERT INTO skills (name, category) VALUES
('Python', 'technical'),
('JavaScript', 'technical'),
('TypeScript', 'technical'),
('Java', 'technical'),
('C++', 'technical'),
('C#', 'technical'),
('Go', 'technical'),
('Rust', 'technical'),
('PHP', 'technical'),
('Ruby', 'technical'),
('SQL', 'technical'),
('PostgreSQL', 'technical'),
('MySQL', 'technical'),
('MongoDB', 'technical'),
('Redis', 'technical'),
('Docker', 'technical'),
('Kubernetes', 'technical'),
('Git', 'technical'),
('Linux', 'technical'),
('Bash', 'technical'),
('CI/CD', 'technical'),
('REST API', 'technical'),
('GraphQL', 'technical'),
('React', 'technical'),
('Vue.js', 'technical'),
('Angular', 'technical'),
('Node.js', 'technical'),
('Django', 'technical'),
('Flask', 'technical'),
('Spring Boot', 'technical'),
('FastAPI', 'technical'),
('TensorFlow', 'technical'),
('PyTorch', 'technical'),
('Scikit-learn', 'technical'),
('Pandas', 'technical'),
('NumPy', 'technical'),
('OpenCV', 'technical'),
('Computer Vision', 'technical'),
('NLP', 'technical'),
('Machine Learning', 'technical'),
('Deep Learning', 'technical'),
('Data Analysis', 'technical'),
('Data Engineering', 'technical'),
('ETL', 'technical'),
('Apache Kafka', 'technical'),
('RabbitMQ', 'technical'),
('AWS', 'technical'),
('Azure', 'technical'),
('Google Cloud', 'technical'),
('Terraform', 'technical'),
('Ansible', 'technical'),
('Prometheus', 'technical'),
('Grafana', 'technical'),
('Jenkins', 'technical'),
('GitLab CI', 'technical'),
('GitHub Actions', 'technical'),
('Microservices', 'technical'),
('OAuth2', 'technical'),
('JWT', 'technical'),
('Blockchain', 'technical'),
('Solidity', 'technical'),
('Web3', 'technical'),
('Cybersecurity', 'technical'),
('Penetration Testing', 'technical'),
('Network Security', 'technical'),
('Cryptography', 'technical'),
('DevOps', 'technical'),
('MLOps', 'technical'),
('Agile', 'methodology'),
('Scrum', 'methodology'),
('Kanban', 'methodology'),
('Jira', 'tool'),
('Confluence', 'tool'),
('Notion', 'tool'),
('Figma', 'tool'),
('Postman', 'tool'),
('Swagger', 'tool'),
('Tableau', 'tool'),
('Power BI', 'tool'),
('Excel', 'tool'),
('Matlab', 'tool'),
('CAD', 'engineering'),
('SolidWorks', 'engineering'),
('AutoCAD', 'engineering'),
('MATLAB Simulink', 'engineering'),
('PLC Programming', 'engineering'),
('Embedded Systems', 'engineering'),
('RTOS', 'engineering'),
('FPGA', 'engineering'),
('Verilog', 'engineering'),
('VHDL', 'engineering'),
('Robotics', 'engineering'),
('IoT', 'engineering'),
('5G', 'engineering'),
('RF Engineering', 'engineering'),
('Signal Processing', 'engineering'),
('Control Systems', 'engineering'),
('Thermodynamics', 'engineering'),
('Fluid Dynamics', 'engineering'),
('Mechanical Design', 'engineering'),
('Electrical Engineering', 'engineering'),
('Power Electronics', 'engineering'),
('PCB Design', 'engineering'),
('Altium Designer', 'engineering'),
('OrCAD', 'engineering'),
('English (B1)', 'language'),
('English (B2)', 'language'),
('English (C1)', 'language'),
('German', 'language'),
('Chinese', 'language'),
('French', 'language'),
('Spanish', 'language'),
('Data Visualization', 'technical'),
('Big Data', 'technical'),
('Hadoop', 'technical'),
('Spark', 'technical'),
('Airflow', 'technical'),
('dbt', 'technical'),
('Looker', 'tool'),
('Metabase', 'tool'),
('Superset', 'tool'),
('ClickHouse', 'technical'),
('Elasticsearch', 'technical'),
('Kibana', 'tool'),
('Logstash', 'technical'),
('Fluentd', 'technical'),
('Nginx', 'technical'),
('Apache', 'technical'),
('Traefik', 'technical'),
('Istio', 'technical'),
('Service Mesh', 'technical'),
('OAuth', 'technical'),
('SAML', 'technical'),
('LDAP', 'technical'),
('Active Directory', 'technical'),
('Zero Trust', 'security'),
('SIEM', 'security'),
('IDS/IPS', 'security'),
('Vulnerability Scanning', 'security'),
('Compliance (GDPR)', 'security'),
('Compliance (ISO 27001)', 'security'),
('Risk Assessment', 'security'),
('Incident Response', 'security'),
('Digital Forensics', 'security'),
('Cloud Security', 'security'),
('Container Security', 'security'),
('API Security', 'security'),
('Secure Coding', 'security'),
('Threat Modeling', 'security'),
('QA', 'technical'),
('Manual Testing', 'technical'),
('Automated Testing', 'technical'),
('Selenium', 'technical'),
('Cypress', 'technical'),
('Playwright', 'technical'),
('JUnit', 'technical'),
('PyTest', 'technical'),
('Load Testing', 'technical'),
('JMeter', 'technical'),
('Locust', 'technical'),
('Accessibility (a11y)', 'technical'),
('SEO', 'technical'),
('UX Research', 'design'),
('UI Design', 'design'),
('User Testing', 'design'),
('Wireframing', 'design'),
('Prototyping', 'design'),
('Design Systems', 'design'),
('Responsive Design', 'design'),
('Cross-browser Compatibility', 'technical'),
('Web Performance', 'technical'),
('Lighthouse', 'tool'),
('Webpack', 'tool'),
('Vite', 'tool'),
('Rollup', 'tool'),
('Babel', 'tool'),
('ESLint', 'tool'),
('Prettier', 'tool'),
('Yarn', 'tool'),
('npm', 'tool'),
('pnpm', 'tool'),
('Rust (embedded)', 'technical'),
('Zig', 'technical'),
('Assembly', 'technical'),
('Quantum Computing', 'emerging'),
('AR/VR Development', 'emerging'),
('Unity', 'tool'),
('Unreal Engine', 'tool'),
('Game Development', 'technical'),
('Audio Programming', 'technical'),
('3D Modeling', 'design'),
('Blender', 'tool'),
('Maya', 'tool'),
('Digital Twin', 'emerging'),
('Edge Computing', 'technical'),
('Serverless', 'technical'),
('AWS Lambda', 'technical'),
('Azure Functions', 'technical'),
('Google Cloud Functions', 'technical'),
('Firebase', 'technical'),
('Supabase', 'technical'),
('Hasura', 'technical'),
('Prisma', 'tool'),
('TypeORM', 'tool'),
('Sequelize', 'tool'),
('SQLAlchemy', 'tool'),
('Alembic', 'tool'),
('Liquibase', 'tool'),
('Flyway', 'tool'),
('Database Migration', 'technical'),
('Indexing', 'technical'),
('Query Optimization', 'technical'),
('Replication', 'technical'),
('Sharding', 'technical'),
('Backup & Recovery', 'technical'),
('Disaster Recovery', 'technical'),
('High Availability', 'technical'),
('Load Balancing', 'technical'),
('CDN', 'technical'),
('WebSockets', 'technical'),
('gRPC', 'technical'),
('Protocol Buffers', 'technical'),
('Message Queues', 'technical'),
('Event-Driven Architecture', 'technical'),
('Domain-Driven Design', 'methodology'),
('Clean Architecture', 'methodology'),
('TDD', 'methodology'),


--- софт навыки ---

INSERT INTO skills (name, category) VALUES
('Коммуникабельность', 'soft'),
('Работа в команде', 'soft'),
('Решение проблем', 'soft'),
('Критическое мышление', 'soft'),
('Тайм-менеджмент', 'soft'),
('Лидерство', 'soft'),
('Гибкость', 'soft'),
('Креативность', 'soft'),
('Эмоциональный интеллект', 'soft'),
('Разрешение конфликтов', 'soft'),
('Навыки ведения переговоров', 'soft'),
('Публичные выступления', 'soft'),
('Активное слушание', 'soft'),
('Ориентация на клиента', 'soft'),
('Внимание к деталям', 'soft'),
('Самомотивация', 'soft'),
('Стрессоустойчивость', 'soft'),
('Управление проектами', 'soft'),
('Стратегическое мышление', 'soft'),
('Принятие решений', 'soft'),
('Наставничество', 'soft'),
('Коучинг', 'soft'),
('Навыки презентации', 'soft'),
('Письменная коммуникация', 'soft'),
('Аналитическое мышление', 'soft'),
('Исследовательские навыки', 'soft'),
('Организационные навыки', 'soft'),
('Инициативность', 'soft'),
('Ответственность', 'soft'),
('Эмпатия', 'soft'),
('Умение делегировать', 'soft'),
('Работа в условиях неопределённости', 'soft'),
('Многозадачность', 'soft'),
('Самоорганизация', 'soft'),
('Этичное поведение', 'soft'),
('Проактивность', 'soft'),
('Обратная связь (умение давать и принимать)', 'soft'),
('Культурная осведомлённость', 'soft'),
('Способность к обучению', 'soft'),
('Адаптивность к изменениям', 'soft'),
('Фокус на результате', 'soft'),
('Построение доверительных отношений', 'soft'),
('Умение работать с возражениями', 'soft'),
('Саморефлексия', 'soft'),
('Управление ожиданиями', 'soft'),
('Работа с обратной связью', 'soft'),
('Эффективное планирование', 'soft'),
('Навыки фасилитации', 'soft'),
('Медиация', 'soft')
ON CONFLICT (name) DO NOTHING;

