# Generated by Django 4.2.7 on 2025-10-18 10:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Желаемая должность')),
                ('summary', models.TextField(blank=True, verbose_name='О себе')),
                ('experience_level', models.CharField(choices=[('no_experience', 'Без опыта'), ('junior', 'Junior (1-3 года)'), ('middle', 'Middle (3-5 лет)'), ('senior', 'Senior (5+ лет)'), ('lead', 'Lead/Team Lead')], default='junior', max_length=20, verbose_name='Уровень опыта')),
                ('education_level', models.CharField(choices=[('secondary', 'Среднее'), ('specialized', 'Среднее специальное'), ('bachelor', 'Бакалавр'), ('master', 'Магистр'), ('phd', 'Кандидат наук'), ('doctor', 'Доктор наук')], default='bachelor', max_length=20, verbose_name='Уровень образования')),
                ('university', models.CharField(blank=True, max_length=200, verbose_name='Университет')),
                ('faculty', models.CharField(blank=True, max_length=200, verbose_name='Факультет')),
                ('graduation_year', models.PositiveIntegerField(blank=True, null=True, verbose_name='Год окончания')),
                ('skills', models.TextField(blank=True, verbose_name='Навыки')),
                ('languages', models.TextField(blank=True, verbose_name='Языки')),
                ('salary_expectation', models.PositiveIntegerField(blank=True, null=True, verbose_name='Желаемая зарплата')),
                ('is_remote', models.BooleanField(default=False, verbose_name='Готов к удаленной работе')),
                ('is_relocation', models.BooleanField(default=False, verbose_name='Готов к переезду')),
                ('resume_file', models.FileField(blank=True, null=True, upload_to='resumes/', verbose_name='Файл резюме')),
                ('is_public', models.BooleanField(default=True, verbose_name='Публичное резюме')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='resume', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Резюме',
                'verbose_name_plural': 'Резюме',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkExperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=200, verbose_name='Компания')),
                ('position', models.CharField(max_length=200, verbose_name='Должность')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('start_date', models.DateField(verbose_name='Дата начала')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Дата окончания')),
                ('is_current', models.BooleanField(default=False, verbose_name='Текущее место работы')),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_experiences', to='resumes.resume', verbose_name='Резюме')),
            ],
            options={
                'verbose_name': 'Опыт работы',
                'verbose_name_plural': 'Опыт работы',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institution', models.CharField(max_length=200, verbose_name='Учебное заведение')),
                ('degree', models.CharField(max_length=200, verbose_name='Степень/Специальность')),
                ('start_date', models.DateField(verbose_name='Дата начала')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Дата окончания')),
                ('is_current', models.BooleanField(default=False, verbose_name='Текущее обучение')),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='educations', to='resumes.resume', verbose_name='Резюме')),
            ],
            options={
                'verbose_name': 'Образование',
                'verbose_name_plural': 'Образование',
                'ordering': ['-start_date'],
            },
        ),
    ]
