# Generated by Django 4.2.7 on 2025-10-18 10:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Internship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название стажировки')),
                ('description', models.TextField(verbose_name='Описание')),
                ('requirements', models.TextField(verbose_name='Требования к стажерам')),
                ('tasks', models.TextField(blank=True, verbose_name='Задачи стажеров')),
                ('specialization', models.CharField(max_length=200, verbose_name='Специальность')),
                ('students_count', models.PositiveIntegerField(verbose_name='Количество студентов')),
                ('duration', models.CharField(choices=[('1', '1 месяц'), ('2', '2 месяца'), ('3', '3 месяца'), ('6', '6 месяцев'), ('12', '1 год')], default='3', max_length=10, verbose_name='Продолжительность')),
                ('start_date', models.DateField(verbose_name='Дата начала')),
                ('end_date', models.DateField(verbose_name='Дата окончания')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('pending', 'На модерации'), ('published', 'Опубликована'), ('closed', 'Закрыта'), ('rejected', 'Отклонена')], default='draft', max_length=20, verbose_name='Статус')),
                ('contact_email', models.EmailField(max_length=254, verbose_name='Контактный email')),
                ('contact_phone', models.CharField(blank=True, max_length=20, verbose_name='Контактный телефон')),
                ('is_remote', models.BooleanField(default=False, verbose_name='Удаленная стажировка')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата публикации')),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='internships', to=settings.AUTH_USER_MODEL, verbose_name='Университет')),
            ],
            options={
                'verbose_name': 'Стажировка',
                'verbose_name_plural': 'Стажировки',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InternshipApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(blank=True, verbose_name='Сообщение')),
                ('students_count', models.PositiveIntegerField(verbose_name='Количество студентов')),
                ('status', models.CharField(choices=[('new', 'Новая'), ('viewed', 'Просмотрена'), ('accepted', 'Принята'), ('rejected', 'Отклонена')], default='new', max_length=20, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата заявки')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='internship_applications', to=settings.AUTH_USER_MODEL, verbose_name='Компания')),
                ('internship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='internships.internship', verbose_name='Стажировка')),
            ],
            options={
                'verbose_name': 'Заявка на стажировку',
                'verbose_name_plural': 'Заявки на стажировки',
                'ordering': ['-created_at'],
                'unique_together': {('internship', 'company')},
            },
        ),
    ]
