# Generated by Django 4.2.7 on 2025-10-19 15:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('internships', '0003_update_models_structure'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='internshipapplication',
            options={'ordering': ['-created_at'], 'verbose_name': 'Отклик на стажировку', 'verbose_name_plural': 'Отклики на стажировки'},
        ),
        migrations.AlterUniqueTogether(
            name='internshipapplication',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='internship',
            name='students_count',
        ),
        migrations.AlterField(
            model_name='internship',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='internships', to=settings.AUTH_USER_MODEL, verbose_name='Компания'),
        ),
        migrations.AlterField(
            model_name='internship',
            name='requirements',
            field=models.TextField(verbose_name='Требования'),
        ),
        migrations.AlterField(
            model_name='internship',
            name='tasks',
            field=models.TextField(blank=True, verbose_name='Задачи'),
        ),
        migrations.AlterField(
            model_name='internship',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='internshipapplication',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата отклика'),
        ),
        migrations.AlterField(
            model_name='internshipapplication',
            name='status',
            field=models.CharField(choices=[('new', 'Новый'), ('viewed', 'Просмотрен'), ('interview', 'Собеседование'), ('accepted', 'Принят'), ('rejected', 'Отклонен')], default='new', max_length=20, verbose_name='Статус'),
        ),
        migrations.AlterUniqueTogether(
            name='practiceapplication',
            unique_together={('practice_request', 'hr_company')},
        ),
        migrations.RemoveField(
            model_name='internshipapplication',
            name='message',
        ),
        migrations.RemoveField(
            model_name='internshipapplication',
            name='students_count',
        ),
    ]
