# Generated by Django 4.2.7 on 2025-10-18 10:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Должность')),
                ('description', models.TextField(verbose_name='Описание')),
                ('requirements', models.TextField(verbose_name='Требования')),
                ('responsibilities', models.TextField(blank=True, verbose_name='Обязанности')),
                ('salary_min', models.PositiveIntegerField(blank=True, null=True, verbose_name='Зарплата от')),
                ('salary_max', models.PositiveIntegerField(blank=True, null=True, verbose_name='Зарплата до')),
                ('experience_level', models.CharField(choices=[('no_experience', 'Без опыта'), ('junior', 'Junior (1-3 года)'), ('middle', 'Middle (3-5 лет)'), ('senior', 'Senior (5+ лет)'), ('lead', 'Lead/Team Lead')], default='junior', max_length=20, verbose_name='Уровень опыта')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('pending', 'На модерации'), ('published', 'Опубликована'), ('closed', 'Закрыта'), ('rejected', 'Отклонена')], default='draft', max_length=20, verbose_name='Статус')),
                ('contact_email', models.EmailField(max_length=254, verbose_name='Контактный email')),
                ('contact_phone', models.CharField(blank=True, max_length=20, verbose_name='Контактный телефон')),
                ('is_remote', models.BooleanField(default=False, verbose_name='Удаленная работа')),
                ('auto_close_date', models.DateTimeField(blank=True, null=True, verbose_name='Автозакрытие')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата публикации')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vacancies', to=settings.AUTH_USER_MODEL, verbose_name='Компания')),
            ],
            options={
                'verbose_name': 'Вакансия',
                'verbose_name_plural': 'Вакансии',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cover_letter', models.TextField(blank=True, verbose_name='Сопроводительное письмо')),
                ('resume_file', models.FileField(blank=True, null=True, upload_to='resumes/', verbose_name='Файл резюме')),
                ('status', models.CharField(choices=[('new', 'Новый'), ('viewed', 'Просмотрен'), ('interview', 'Собеседование'), ('accepted', 'Принят'), ('rejected', 'Отклонен')], default='new', max_length=20, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата отклика')),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to=settings.AUTH_USER_MODEL, verbose_name='Кандидат')),
                ('vacancy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='vacancies.vacancy', verbose_name='Вакансия')),
            ],
            options={
                'verbose_name': 'Отклик',
                'verbose_name_plural': 'Отклики',
                'ordering': ['-created_at'],
                'unique_together': {('vacancy', 'candidate')},
            },
        ),
    ]
