# Generated by Django 4.2.7 on 2025-10-19 15:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vacancies', '0002_add_public_bank_field'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='application',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='application',
            name='candidate_email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email кандидата'),
        ),
        migrations.AddField(
            model_name='application',
            name='candidate_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='Имя кандидата'),
        ),
        migrations.AddField(
            model_name='application',
            name='candidate_phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='Телефон кандидата'),
        ),
        migrations.AlterField(
            model_name='application',
            name='candidate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='applications', to=settings.AUTH_USER_MODEL, verbose_name='Кандидат'),
        ),
    ]
