# Generated by Django 4.2.7 on 2025-10-18 15:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vacancies', '0001_initial'),
        ('resumes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecommendationRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название правила')),
                ('description', models.TextField(verbose_name='Описание правила')),
                ('skill_keywords', models.TextField(blank=True, help_text='Ключевые слова навыков через запятую', verbose_name='Ключевые слова навыков')),
                ('experience_level', models.CharField(blank=True, choices=[('no_experience', 'Без опыта'), ('junior', 'Junior (1-3 года)'), ('middle', 'Middle (3-5 лет)'), ('senior', 'Senior (5+ лет)'), ('lead', 'Lead/Team Lead')], max_length=20, verbose_name='Уровень опыта')),
                ('salary_min', models.PositiveIntegerField(blank=True, null=True, verbose_name='Минимальная зарплата')),
                ('salary_max', models.PositiveIntegerField(blank=True, null=True, verbose_name='Максимальная зарплата')),
                ('is_remote', models.BooleanField(blank=True, null=True, verbose_name='Удаленная работа')),
                ('weight', models.FloatField(default=1.0, verbose_name='Вес правила')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Правило рекомендации',
                'verbose_name_plural': 'Правила рекомендаций',
                'ordering': ['-weight', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HRRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recommendation_type', models.CharField(choices=[('interview', 'Провести собеседование'), ('test', 'Назначить тест'), ('phone', 'Телефонное интервью'), ('reject', 'Отклонить'), ('wait', 'Дождаться дополнительных откликов')], max_length=50, verbose_name='Тип рекомендации')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('description', models.TextField(verbose_name='Описание')),
                ('priority', models.CharField(choices=[('high', 'Высокий'), ('medium', 'Средний'), ('low', 'Низкий')], default='medium', max_length=20, verbose_name='Приоритет')),
                ('is_completed', models.BooleanField(default=False, verbose_name='Выполнено')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hr_recommendations', to='vacancies.application', verbose_name='Отклик')),
            ],
            options={
                'verbose_name': 'Рекомендация HR',
                'verbose_name_plural': 'Рекомендации HR',
                'ordering': ['-priority', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ResumeRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(verbose_name='Оценка совпадения')),
                ('matched_rules', models.TextField(default='[]', verbose_name='Совпавшие правила')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vacancy_recommendations', to='resumes.resume', verbose_name='Резюме')),
                ('vacancy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resume_recommendations', to='vacancies.vacancy', verbose_name='Вакансия')),
            ],
            options={
                'verbose_name': 'Рекомендация резюме',
                'verbose_name_plural': 'Рекомендации резюме',
                'ordering': ['-score', '-created_at'],
                'unique_together': {('vacancy', 'resume')},
            },
        ),
    ]
